name: main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  typecheck:
    name: Type Checking
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run TypeScript type check
        run: npm run typecheck

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: typecheck
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Bump Version
        run: npm version patch --no-git-tag-version

      - name: Install dependencies
        run: npm ci

      - name: Install @vitest/coverage-v8 manually
        run: npm install --save-dev @vitest/coverage-v8

      - name: Run tests and generate coverage report
        run: npm test --coverage

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage
          retention-days: 5

  publish:
    permissions:
      contents: read
      packages: write

    name: Publish Package
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.org


      - name: Install Dependencies
        run: npm install

      - name: Bump Version
        run: npm version patch --no-git-tag-version

      - name: Setup npm auth
        run: |
          echo "@gudlaugvest:registry=https://npm.pkg.github.com/" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc

      - name: Publish to GitHub Packages
        run: npm publish --access public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Run ESLint
        run: npx eslint .